
#Do you want enchantments?
[Enchanting]
	#Want to smelt things when you mine them?
	enableBlazing = true
	#Want to jump more than a block high with an enchantment?
	enableHops = true
	#Want more speed with an enchantment?
	enableNimble = true
	#Don't want the zombies stealing your items when you are mining?
	enableSiphon = true
	#Want all the experience in the nearby area?
	enableVeteran = true
	#Want more health with an enchant?
	enableVigor = true
	#Don't want to aim but love shooting arrows?
	enableHoming = true

