
[features]
	#If set true, tools may drop an item when they'll be used.
	extraDrop = true
	#If set true, bone axe and sword make extra damage against special mobs.
	extraDamage = true
	#If set to true the corresponding ore of the tool drops an additional resource.
	doubleDrop = true
	#If set to true paper tools may hurt you.
	damageByPaperTools = true
	#If set true, (wither) skeletons will drop their head with a defined chance if killed with bone axe or sword.
	headDrop = true
	#If set true, using Fiery tools to mine blocks will smelt them.
	autoSmelt = true

	[features.doubleDropBool]
		#Diamond available for hammers/excavators
		diamond = true
		coal = true
		quartz = true
		lapis = true
		emerald = true
		redstone = true

[chances]

	[chances.doubleDropValue]
		#Default 1 = 0.1%
		#Range: 0 ~ 1000
		diamond = 1
		#Range: 0 ~ 1000
		coal = 500
		#Range: 0 ~ 1000
		quartz = 500
		#Range: 0 ~ 1000
		lapis = 500
		#Default 1 = 0.1%
		#Range: 0 ~ 1000
		emerald = 1
		#Range: 0 ~ 1000
		redstone = 500

	[chances.extraDropValue]
		#Sets the chance of an extra drop when using a tool. [Default 5 = 0.5%]
		#Range: 0 ~ 1000
		extraDrop = 5
		#Sets the chance of extra damage when using bone axe or sword on a (wither) skeleton. [Default 200 = 20%]
		#Range: 0 ~ 1000
		extraDamage = 200
		#Sets the chance to take an half heart damage if using paper tools. [Default 100 = 10%]
		#Range: > 0
		damageByPaperTools = 100
		#Sets the chance of an head drop when using bone axe or sword. [Default 50 = 5%]
		#Range: 0 ~ 1000
		headDrop = 50

[amounts]
	#The maximum amount of damage. Default: 5 = 2.5 hearts
	#Range: > 0
	maxPaperDamage = 5
	#The minimum amount of damage. Default: 1 = 0.5 hearts
	#Range: > 0
	minPaperDamage = 1

	[amounts.durabilities]
		#Range: > 1
		prismarine = 750
		#Range: > 1
		nether = 280
		#Range: > 1
		obsidian = 2674
		#Range: > 1
		fiery = 750
		#Range: > 1
		quartz = 155
		#The durability of the tools
		#Range: > 1
		bone = 206
		#Range: > 1
		ender = 1859
		#Range: > 1
		glowstone = 193
		#Range: > 1
		slime = 1500
		#Range: > 1
		paper = 13
		#Range: > 1
		coal = 155
		#Range: > 1
		lapis = 193
		#Range: > 1
		emerald = 1859
		#Range: > 1
		redstone = 193

	[amounts.miningspeed]
		#Range: 0.0 ~ 2.147483647E9
		prismarine = 7.0
		#Range: 0.0 ~ 2.147483647E9
		nether = 4.9
		#Range: 0.0 ~ 2.147483647E9
		obsidian = 8.2
		#Range: 0.0 ~ 2.147483647E9
		fiery = 7.0
		#Range: 0.0 ~ 2.147483647E9
		quartz = 4.9
		#Range: 0.0 ~ 2.147483647E9
		bone = 4.9
		#Range: 0.0 ~ 2.147483647E9
		ender = 5.7
		#Range: 0.0 ~ 2.147483647E9
		glowstone = 5.0
		#Range: 0.0 ~ 2.147483647E9
		stone = 4.0
		#Range: 0.0 ~ 2.147483647E9
		slime = 6.2
		#Range: 0.0 ~ 2.147483647E9
		gold = 11.0
		#Range: 0.0 ~ 2.147483647E9
		diamond = 8.0
		#Range: 0.0 ~ 2.147483647E9
		paper = 1.8
		#Range: 0.0 ~ 2.147483647E9
		iron = 6.0
		#Range: 0.0 ~ 2.147483647E9
		coal = 4.9
		#The mining speed of the tools. Will be devided by 3.5 for hammers/excavators.
		#Range: 0.0 ~ 2.147483647E9
		wood = 2.0
		#Range: 0.0 ~ 2.147483647E9
		lapis = 6.2
		#Range: 0.0 ~ 2.147483647E9
		emerald = 8.2
		#Range: 0.0 ~ 2.147483647E9
		redstone = 6.2

	[amounts.harvestlevels]
		#Range: 0 ~ 4
		prismarine = 3
		#Range: 0 ~ 4
		nether = 1
		#Range: 0 ~ 4
		obsidian = 4
		#Range: 0 ~ 4
		fiery = 3
		#Range: 0 ~ 4
		quartz = 2
		#Range: 0 ~ 4
		bone = 1
		#Range: 0 ~ 4
		ender = 3
		#Range: 0 ~ 4
		glowstone = 2
		#Range: 0 ~ 4
		stone = 1
		#Range: 0 ~ 4
		slime = 2
		#Range: 0 ~ 4
		gold = 0
		#Range: 0 ~ 4
		diamond = 3
		#Range: 0 ~ 4
		paper = 0
		#Range: 0 ~ 4
		iron = 2
		#Range: 0 ~ 4
		coal = 1
		#The harvestlevel of the tools (0 = wood; 1 = stone; 2 = iron; 3 = diamond; 4 = higher)
		#Range: 0 ~ 4
		wood = 0
		#Range: 0 ~ 4
		lapis = 2
		#Range: 0 ~ 4
		emerald = 3
		#Range: 0 ~ 4
		redstone = 2

