
[NAUSEA]
	#The strength of the Nausea effect
	#Range: 0.0 ~ 10.0
	nauseaModifier = 0.15
	#NORMAL - Players stumble when moving, ADVANCED - Players stumble even when standing still
	#Allowed Values: DISABLED, NORMAL, ADVANCED
	stumbling = "DISABLED"

[PORTAL]
	#The strength of the portal distortion effect
	#Range: 0.0 ~ 10.0
	portalModifier = 0.25

