
#Enable or disable certain blocks or entities.
["Accessibility Config"]
	#Whether or not Infested Flower should be generated in mushroom biomes.
	infestedFlowerEnabled = true
	#Whether or not poisonous mushrooms should be generated.
	poisonousMushroomGenerationEnabled = true
	#Whether or not Infested Grass should be generated in mushroom biomes.
	infestedGrassEnabled = true
	#Whether or not glowshrooms should be generated.
	glowshroomGenerationEnabled = true
	#Whether or not mega glowshrooms should be generated.
	megaGlowshroomGenerationEnabled = true
	#Whether or not mega poisonous mushrooms should be generated.
	megaPoisonousMushroomGenerationEnabled = true
	#Whether or not Mushroom Sheep entity should spawn in mushroom biomes.
	mushroomSheepEnabled = true
	#Whether or not big poisonous mushrooms should be generated.
	bigPoisonousMushroomGenerationEnabled = true
	#Whether or not big glowshrooms should be generated.
	bigGlowshroomGenerationEnabled = true
	#Whether or not vanilla mega mushrooms should be generated in mushroom biomes.
	vanillaMegaMushroomGenerationEnabled = true

#Various options that affect blocks and entities.
["Balance Options"]
	#Maximal group size of spawning Mushroom Sheep herds.
	#Range: 1 ~ 20
	mushroomSheepSpawnMaxGroupCount = 8
	#Count factor of glowshrooms generation. (1.0: generation count of vanilla brown mushroom)
	#Range: 0.0 ~ 10.0
	glowshroomGenerationCountFactor = 0.25
	#Generating chance of big mushrooms in biomes with big mushrooms. (1 - high chance; 100 - low chance)
	#Range: 1 ~ 100
	bigMushroomGenerationChance = 12
	#Whether or not mushroom cap buttons should play a sound when activated.
	mushroomButtonPressurePlatePlaySound = false
	#Weight of big poisonous mushrooms generation.
	#Range: 0.0 ~ 10.0
	bigPoisonousMushroomGenerationWeight = 0.25
	#Weight of mega red mushrooms generation.
	#Range: 0.0 ~ 10.0
	megaRedMushroomGenerationWeight = 1.0
	#Whether or not mushroom cap pressure plates should play a sound when stepped on or off.
	mushroomCapPressurePlatePlaySound = false
	#Chance factor of glowshrooms generation. (1.0: generation chance of vanilla brown mushroom)
	#Range: 0.0 ~ 10.0
	glowshroomGenerationChanceFactor = 0.25
	#Minimal group size of spawning Mushroom Sheep herds.
	#Range: 1 ~ 20
	mushroomSheepSpawnMinGroupCount = 4
	#Chance factor of poisonous mushrooms generation. (1.0: generation chance of vanilla brown mushroom)
	#Range: 0.0 ~ 10.0
	poisonousMushroomGenerationChanceFactor = 0.25
	#Generating chance of mega mushrooms in mushroom biomes. (1 - high chance; 100 - low chance)
	#Range: 1 ~ 100
	megaMushroomGenerationChance = 12
	#Weight of mega brown mushrooms generation.
	#Range: 0.0 ~ 10.0
	megaBrownMushroomGenerationWeight = 1.0
	#Weight of mega poisonous mushrooms generation.
	#Range: 0.0 ~ 10.0
	megaPoisonousMushroomGenerationWeight = 0.25
	#Whether or not sheeps and mushroom sheeps change their fleece to the mushroom type when eating a mushroom from ground or while feeding.
	sheepAbsorbMushroomTypeEnabled = true
	#Whether or not sheeps and mushroom sheeps can eat mushrooms from ground.
	sheepEatMushroomFromGroundEnabled = true
	#Weight of big glowshrooms generation.
	#Range: 0.0 ~ 10.0
	bigGlowshroomGenerationWeight = 0.25
	#Count factor of poisonous mushrooms generation. (1.0: generation count of vanilla brown mushroom)
	#Range: 0.0 ~ 10.0
	poisonousMushroomGenerationCountFactor = 0.25
	#Spawn weight of Mushroom Sheep. (Example: Mooshroom in mushroom biome has weight of 8)
	#Range: 1 ~ 100
	mushroomSheepSpawnWeight = 8
	#Weight of mega glowshrooms generation.
	#Range: 0.0 ~ 10.0
	megaGlowshroomGenerationWeight = 0.25

