
[worldgen]
	enabled = true

	[worldgen.tin]
		#Range: > 1
		chance = 10
		#Range: > 0
		min_height = 0
		#Range: > 1
		size = 6
		#Range: > 0
		max_height = 64
		enabled = true

	[worldgen.copper]
		#Range: > 1
		chance = 15
		#Range: > 0
		min_height = 0
		#Range: > 1
		size = 10
		#Range: > 0
		max_height = 68
		enabled = true

