
#General Settings (COMMON)
[GENERAL]
	#Enable magic mirror recipe
	ingredientsEnabled = false
	#Enable recipes for dimensional mirrors
	dimensionalMirrorsEnabled = true

#Developer Settings
[DEVELOPER]
	#Enable / Disable LogManager logging (DEV)
	logger = false

