
[general]
	#Smallest value attack reach attribute is allowed to have. Needs to be smaller than "Attack Reach Max". Changes require a restart to apply.
	#Range: -2.147483648E9 ~ 2.147483647E9
	"Attack Reach Min" = 0.0
	#Largest value attack reach attribute is allowed to have. Needs to be greater than "Attack Reach Min". Changes require a restart to apply.
	#Range: -2.147483648E9 ~ 2.147483647E9
	"Attack Reach Max" = 1024.0

#Set default values for all attributes used by the player.
#Actual range might differ with certain mods like "AttributeFix" installed. Changes require relogging to apply.
[default_attribute_values]
	#Chance to not receive any knockback from an attack.
	#Actual Range: 0.0 ~ 1.0
	#Range: -2.147483648E9 ~ 2.147483647E9
	"Default Knockback Resistance" = 0.0
	#Speed at which the attack cooldown recharges, higher values make it recharge faster.
	#Actual Range: 0.0 ~ 1024.0
	#Range: -2.147483648E9 ~ 2.147483647E9
	"Default Attack Speed" = 4.0
	#Amount of health when fully healed.
	#Actual Range: 0.0 ~ 1024.0
	#Range: -2.147483648E9 ~ 2.147483647E9
	"Default Max Health" = 20.0
	#Number of blocks for interacting with entities, 2.0 is added when in creative mode.
	#Actual Range: 0.0 ~ 1024.0
	#Range: -2.147483648E9 ~ 2.147483647E9
	"Default Attack Reach" = 3.0
	#Vertical motion multiplier, mainly used when falling.
	#Actual Range: -8.0 ~ 8.0
	#Range: -2.147483648E9 ~ 2.147483647E9
	"Default Gravity" = 0.08
	#Movement speed when swimming in of water.
	#Actual Range: 0.0 ~ 1024.0
	#Range: -2.147483648E9 ~ 2.147483647E9
	"Default Swim Speed" = 1.0
	#Luck property when using loot tables.
	#Actual Range: -1024.0 ~ 1024.0
	#Range: -2.147483648E9 ~ 2.147483647E9
	"Default Luck" = 0.0
	#Distance for interacting with blocks in the world, 0.5 is added when in creative mode.
	#Actual Range: 0.0 ~ 1024.0
	#Range: -2.147483648E9 ~ 2.147483647E9
	"Default Reach Distance" = 4.5
	#Amount of armor toughness.
	#Actual Range: 0.0 ~ 20.0
	#Range: -2.147483648E9 ~ 2.147483647E9
	"Default Armor Toughness" = 0.0
	#Movement speed when walking on land.
	#Actual Range: 0.0 ~ 1024.0
	#Range: -2.147483648E9 ~ 2.147483647E9
	"Default Movement Speed" = 0.1
	#Amount of armor protection.
	#Actual Range: 0.0 ~ 30.0
	#Range: -2.147483648E9 ~ 2.147483647E9
	"Default Armor" = 0.0
	#Amount of melee damage dealt when fighting.
	#Actual Range: 0.0 ~ 2048.0
	#Range: -2.147483648E9 ~ 2.147483647E9
	"Default Attack Damage" = 1.0
	#How much knockback is dealt when hitting an entity.
	#Actual Range: 0.0 ~ 5.0
	#Range: -2.147483648E9 ~ 2.147483647E9
	"Default Attack Knockback" = 0.0

#Allows changing various attribute stats of items. Provided values are added to the attribute, they will not replace it.
#For base values check defaults section of the config. Actual range might differ with certain mods like "AttributeFix" installed.
#Format for every entry is "<namespace>:<path>,<value>". Path may use single asterisk as wildcard parameter.
[attribute_item_stats]
	#Amount of armor toughness.
	#Actual Range: 0.0 ~ 20.0
	"Armor Toughness List" = []
	#How much knockback is dealt when hitting an entity.
	#Actual Range: 0.0 ~ 5.0
	"Attack Knockback List" = []
	#Movement speed when swimming in of water.
	#Actual Range: 0.0 ~ 1024.0
	"Swim Speed List" = []
	#Speed at which the attack cooldown recharges, higher values make it recharge faster.
	#Actual Range: 0.0 ~ 1024.0
	"Attack Speed List" = []
	#Movement speed when walking on land.
	#Actual Range: 0.0 ~ 1024.0
	"Movement Speed List" = []
	#Luck property when using loot tables.
	#Actual Range: -1024.0 ~ 1024.0
	"Luck List" = []
	#Amount of melee damage dealt when fighting.
	#Actual Range: 0.0 ~ 2048.0
	"Attack Damage List" = []
	#Number of blocks for interacting with entities.
	#Actual Range: 0.0 ~ 1024.0
	"Attack Reach List" = []
	#Amount of health when fully healed.
	#Actual Range: 0.0 ~ 1024.0
	"Max Health List" = []
	#Distance for interacting with blocks in the world.
	#Actual Range: 0.0 ~ 1024.0
	"Reach Distance List" = []
	#Vertical motion multiplier, mainly used when falling.
	#Actual Range: -8.0 ~ 8.0
	"Gravity List" = []
	#Amount of armor protection.
	#Actual Range: 0.0 ~ 30.0
	"Armor List" = []
	#Chance to not receive any knockback from an attack.
	#Actual Range: 0.0 ~ 1.0
	"Knockback Resistance List" = []

#Allows changing various property stats of items.
#Format for every entry is "<namespace>:<path>,<value>". Path may use single asterisk as wildcard parameter.
[property_item_stats]
	#Specify max stack size for any item.
	#Actual Range: 0.0 ~ 64.0
	#Condition: Must not have durability
	"Stack Size List" = []
	#Change dig speed value for any item.
	#Setting to 0 will prevent the item from mining anything.
	#Actual Range: 0.0 ~ 2.147483647E9
	"Dig Speed List" = []
	#Change enchantability value for any enchantable item.
	#Setting to 0 will make enchanting this item impossible.
	#Actual Range: 0.0 ~ 2.147483647E9
	#Condition: Must be enchantable
	"Enchantability List" = []
	#Change durability for any damageable item.
	#Setting to 0 will make the item unbreakable.
	#Actual Range: 0.0 ~ 2.147483647E9
	#Condition: Must have durability
	"Durability List" = []
	#Change harvest level value for any tool item.
	#Setting to -1 will remove any harvest level present.
	#Actual Range: 0.0 ~ 2.147483647E9
	#Condition: Must be a tool
	"Harvest Level List" = []

