
#CommonConfig Config
[CommonConfig]
	#set to true for PARACHUTE single use [default: false]
	singleUse = false
	#if true, allow riding in water [default: true]
	rideInWater = true
	#enable fuel burn rise by pressing the space bar [default: true]
	#only applies to the powered parachute
	allowFulBurn = true

