
#Configuration for Pretty Beaches
[common]
	#Whether the flooding of adjacent air blocks should be animated or instant.
	animatedFlooding = true
	#List of blocks that should be affected by the adjusted water physics.
	affectedBlocks = ["minecraft:sand"]

