
[Ruins]
	#Ruins that spawn underground with different types according to biome.
	"UndergroundRuins enabled" = true
	#Large underground complexes with rare treasure.
	"Vaults enabled" = true

	[Ruins.UndergroundRuins]
		#Default ruin size.
		"Default size" = 2
		#Add a stone marker on the surface above a ruin.
		"Add marker" = true
		#If true, underground ruin maps will be added to dungeon loot and nether fortress chests.
		"Add underground ruin maps to loot" = true
		#Ruin size is increased randomly by this amount.
		"Additional pieces" = 2
		#Chance (out of 1.0) of a marker spawning on the surface above a ruin.
		"Marker chance" = 0.75
		#Distance between ruin structures. For reference, shipwrecks are 16.
		Distance = 20

	[Ruins.Vaults]
		#Vaults size. This controls how many corridors and rooms will spawn.
		"Vault size" = 8
		#If true, vaults will only generate in the Outerlands.
		#This has no effect if the Outerlands module is disabled.
		"Outerlands only" = true
		#Vaults will try and generate below this Y value.
		"Generate below Y value" = 68
		#Vaults will try and generate above this Y value.
		"Generate above Y value" = 24

[Enchantments]
	"LegendaryWeapons enabled" = true
	"IceAspect enabled" = true
	#Treasure items and Legendary items are specially enchanted weapons and tools found in Vaults.
	"TreasureEnchantments enabled" = true
	"EldritchBow enabled" = true
	"LegendaryCrossbow enabled" = true
	"Shulking enabled" = true
	"Repel enabled" = true
	"Growth enabled" = true
	"LegendaryTools enabled" = true
	"LegendaryBow enabled" = true

	[Enchantments.LegendaryWeapons]
		#Valid enchantments that can be applied to Legendary swords.
		"Valid enchantments" = ["minecraft:sharpness", "minecraft:smite", "minecraft:bane_of_arthropods", "minecraft:knockback", "minecraft:fire_aspect", "minecraft:looting", "minecraft:sweeping", "strange:ice_aspect", "strange:repel", "strange:shulking"]

	[Enchantments.LegendaryTools]
		#Valid enchantments that can be applied to Legendary tools.
		"Valid enchantments" = ["minecraft:efficiency", "minecraft:fortune", "minecraft:knockback", "strange:repel", "strange:shulking"]

	[Enchantments.TreasureEnchantments]
		#If true, Strange treasure enchantments can only be found in Vaults, not normal dungeon loot.
		"Only in vaults" = true
		#If true, Strange treasure enchantments can be applied to
		#books or tools on an enchanting table or anvil.
		"Obtainable enchantments" = false
		#The potential number of additional levels above the enchantment's maximum level.
		#An item can never be enchanted higher than level 10.
		"Legendary levels" = 3

	[Enchantments.LegendaryCrossbow]
		#Valid enchantments that can be applied to Legendary crossbows.
		"Valid enchantments" = ["minecraft:quick_charge", "minecraft:piercing"]

	[Enchantments.LegendaryBow]
		#Valid enchantments that can be applied to Legendary bows.
		"Valid enchantments" = ["minecraft:power", "minecraft:punch"]

[Scrolls]
	#Scrolls contain information about quests.
	#They can be found in chests or bought from scrollkeeper villagers.
	"Scrolls enabled" = true

	[Scrolls.Scrollkeepers]
		#Range (in blocks) that a scrollkeeper will indicate that they are ready to accept a completed quest.
		"Villager interest range" = 16
		#Chance (out of 1.0) of a Bad Omen effect being applied after quest completion.
		#The chance and severity of the Bad Omen effect increases with Scrollkeeper level and distance from spawn.  Set to zero to disable Bad Omen effect.
		"Bad Omen chance" = 0.03

	[Scrolls.Quests]
		#Distance from quest start (in blocks) that a mob will spawn for 'encounter' quests.
		"Encounter distance" = 600
		#Distance from quest start (in blocks) that a treasure chest will spawn for 'locate' quests.
		"Locate distance" = 400
		#Maximum number of quests a player can do at once (Maximum 3)
		"Maximum quests" = 2
		#Language code to use for showing quest details.
		Language = "en"

[TravelJournal]
	#Records interesting places around your world.
	"TravelJournal enabled" = true

	[TravelJournal.TravelJournal]
		#Maximum number of entries a single travel journal can hold.
		"Maximum entries" = 30

[Ambience]
	#Ambient background sounds according to the biome, time of day and depth below surface.
	"Ambience enabled" = true

	[Ambience.Ambience]
		#If true, custom music tracks will play in certain situations.
		#Charm's 'Ambient Music Improvements' module must be enabled for this to work.
		"Play music" = true
		#If true, background ambient sounds play in biomes, caves and other dimensions.
		"Play ambient sounds" = true

[Outerlands]
	#Illusioners may spawn in Dark Forests in the Outerlands.
	#If Outerlands is disabled, Illusioners may spawn anywhere.
	"IllusionersInDarkForest enabled" = true
	#A distant area of the overworld with more difficult mobs and better treasure.Can be found by completing quests for a scrollkeeper villager.
	"Outerlands enabled" = true

	[Outerlands.IllusionersInDarkForest]
		#The higher this value, the more Illusioners will spawn. For comparison, zombie weight is 100.
		"Spawn weight" = 50

	[Outerlands.Outerlands]
		#If true, some features will scale their difficulty or reward based on distance from spawn point.
		"Scale by distance" = true
		#If true, monsters will use the distance scaling to become more challenging in the Outerlands.
		"Scary monsters" = true
		#After scaling based on distance, the result will be multiplied by this value.
		#Setting this to a high value will make some monsters extremely hard to beat.
		"Scale difficulty value" = 1.25
		#X or Z axis values greater than this value are considered 'outer lands'.
		Threshold = 15000000

[Totems]
	"TotemOfReturning enabled" = true
	"TotemOfEnchanting enabled" = true
	"TotemOfPreserving enabled" = false
	"TotemOfShielding enabled" = true
	#An Illusioner drops a totem when killed by a player.
	"IllusionersDropTotems enabled" = true
	"TotemOfFlying enabled" = false
	"VillagersTradeTotems enabled" = true
	"TreasureTotems enabled" = true
	"TotemOfTransferring enabled" = true

	[Totems.VillagersTradeTotems]
		#If true, only merchants from 'outer lands' villages have totem trades.
		#This has no effect if the Outerlands module is disabled.
		"Outer villagers only" = true
		#Minimum number of emeralds required to buy a totem.
		"Base buy cost" = 8
		#Level at which a merchant will trade totems.
		"Trade level" = 1
		#Maximum additional emeralds required to buy.
		"Additional cost" = 16

	[Totems.TreasureTotems]
		#If true, Strange treasure totems can only be found in Vaults, not normal dungeon loot.
		"Only in vaults" = true

	[Totems.IllusionersDropTotems]
		#Chance (out of 1.0) of an Illusioner dropping a totem when killed by the player.
		"Drop chance" = 1.0
		#List of totems that may be dropped by an Illusioner.If these totems are disabled, the Illusioner will drop a Totem of Undying.
		"Dropped totems" = ["strange:totem_of_undying", "strange:totem_of_returning", "strange:totem_of_shielding"]
		#If true, Illusioners only drop totems when in the Outerlands.
		"Only drop when in Outerlands" = true

	[Totems.TotemOfPreserving]
		#The totem will stay suspended in the air above your death position.
		"No gravity" = true
		#When you die, your items will be stored in a totem at the place where you died.
		"Save items on death" = true
		#The totem will never despawn.
		"No despawn" = true

	[Totems.TotemOfShielding]
		#Player damage is multiplied by this amount before being transferred to the totem.
		"Damage multiplier" = 0.5
		#Durability of the totem.
		Durability = 128

	[Totems.TotemOfFlying]
		#Number of seconds of flying before some XP is consumed.
		"XP interval" = 1.0
		#Amount of XP consumed while flying.
		"XP amount" = 1
		#Durability of the totem. The totem takes a point of damage every time you take off.
		Durability = 32

[Base]
	#Client to server communication options.
	#If disabled, ambient sounds won't work properly as the client won't be able to access extra world state.
	"Base enabled" = true

	[Base.EntitySpawner]
		#Player will trigger EntitySpawner blocks when closer than this distance.
		"Trigger distance" = 16

	[Base.Base]
		#Heartbeat interval to synchronise additional world state to the client.
		"Client/Server update ticks" = 120

[Runestones]
	#Runestones allow fast travel to points of interest in your world by using an Ender Pearl.
	"Runestones enabled" = true
	#Stone circles are surface structures of stone pillars with a runestone on top.
	#This module depends on the Runestones module.
	"StoneCircles enabled" = true

	[Runestones.StoneCircles]
		#Holding a compass and an iron ingot under a full moon makes the compass point toward the closest stone circle.
		#Charm's 'Compass Binding' feature must be enabled for this to work.
		"Allow compasses to detect stone circles" = true
		#Biomes that stone circles may generate in.
		"Allowed biomes" = ["plains", "sunflower_plains", "badlands", "badlands_plateau", "wooded_badlands_plateau", "desert", "desert_lakes", "beach", "river", "savanna", "savanna_plateau", "snowy_tundra", "snowy_beach", "frozen_river", "swamp"]
		#If true, stone circle maps will be added to village chests.
		"Add stone circle maps to loot" = true
		#Distance between stone cicles. For reference, shipwrecks are 16.
		Distance = 20

	[Runestones.Runestones]
		#Number of seconds of regeneration and slow-fall when travelling through a stone circle runestone.
		"Travel protection duration" = 6
		#If true, one of the runestones will link to a Big Dungeon from Quark.
		#This module must be enabled in Quark for the feature to work.
		#If false, or Quark is not available, this runestone destination will be a stone circle instead.
		"Runestone for Quark Big Dungeons" = true
		#If true, runestones may be mined with a silk touch pickaxe and crafted vertically into obelisks.
		#Match the obelisk runes with a location in your travel journal to immediately teleport to that location.
		"Allow obelisks" = true
		#Maximum number of blocks that you will be transported from a stone circle runestone.
		"Maximum runestone travel distance" = 4000

