
[generationconfig]
	should_sulfur_spawn_in_nether = true
	should_sulfur_spawn_in_overworld = true
	#Spawn frequency. Default is 8
	#Range: 0 ~ 100
	sulfur_count = 8
	#Default is 6
	#Range: 0 ~ 100
	sulfur_vein_size = 6
	#Default is 0
	#Range: 0 ~ 100
	sulfur_bottom_limit = 0
	#Default is 58
	#Range: 0 ~ 100
	sulfur_upper_limit = 58
	#Spawn frequency. Default is 12
	#Range: 0 ~ 100
	sulfur_nether_count = 12
	#Default is 12
	#Range: 0 ~ 100
	sulfur_nether_vein_size = 12
	#Default is 0
	#Range: 0 ~ 100
	sulfur_nether_bottom_limit = 0
	#Default is 0
	#Range: 0 ~ 100
	sulfur_nether_upper_limit = 0
	#Spawn frequency. Default is 12
	#Range: 0 ~ 100
	potassium_count = 12
	#Default is 10
	#Range: 0 ~ 100
	potassium_vein_size = 10
	#Default is 0
	#Range: 0 ~ 100
	potassium_bottom_limit = 0
	#Default is 0
	#Range: 0 ~ 100
	potassium_upper_limit = 0

